
auth.token=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

defaults.org=cahootz-coop
defaults.project=cahootz-mobile

defaults.url=https://sentry.io/
